
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ItemXmlService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://www.seneroto.com.tr/xml/ItemXmlService.asmx?wsdl")
public class ItemXmlService
    extends Service
{

    private final static URL ITEMXMLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ITEMXMLSERVICE_EXCEPTION;
    private final static QName ITEMXMLSERVICE_QNAME = new QName("http://tempuri.org/", "ItemXmlService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.seneroto.com.tr/xml/ItemXmlService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITEMXMLSERVICE_WSDL_LOCATION = url;
        ITEMXMLSERVICE_EXCEPTION = e;
    }

    public ItemXmlService() {
        super(__getWsdlLocation(), ITEMXMLSERVICE_QNAME);
    }

    public ItemXmlService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITEMXMLSERVICE_QNAME, features);
    }

    public ItemXmlService(URL wsdlLocation) {
        super(wsdlLocation, ITEMXMLSERVICE_QNAME);
    }

    public ItemXmlService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITEMXMLSERVICE_QNAME, features);
    }

    public ItemXmlService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ItemXmlService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ItemXmlServiceSoap
     */
    @WebEndpoint(name = "ItemXmlServiceSoap")
    public ItemXmlServiceSoap getItemXmlServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "ItemXmlServiceSoap"), ItemXmlServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItemXmlServiceSoap
     */
    @WebEndpoint(name = "ItemXmlServiceSoap")
    public ItemXmlServiceSoap getItemXmlServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ItemXmlServiceSoap"), ItemXmlServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns ItemXmlServiceSoap
     */
    @WebEndpoint(name = "ItemXmlServiceSoap12")
    public ItemXmlServiceSoap getItemXmlServiceSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "ItemXmlServiceSoap12"), ItemXmlServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItemXmlServiceSoap
     */
    @WebEndpoint(name = "ItemXmlServiceSoap12")
    public ItemXmlServiceSoap getItemXmlServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ItemXmlServiceSoap12"), ItemXmlServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITEMXMLSERVICE_EXCEPTION!= null) {
            throw ITEMXMLSERVICE_EXCEPTION;
        }
        return ITEMXMLSERVICE_WSDL_LOCATION;
    }

}
