
package ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ItemXmlServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ItemXmlServiceSoap {


    /**
     * 
     * @param upass
     * @param uname
     * @return
     *     returns ws.ArrayOfProducts
     */
    @WebMethod(operationName = "GetProducts", action = "http://tempuri.org/GetProducts")
    @WebResult(name = "GetProductsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetProducts", targetNamespace = "http://tempuri.org/", className = "ws.GetProducts")
    @ResponseWrapper(localName = "GetProductsResponse", targetNamespace = "http://tempuri.org/", className = "ws.GetProductsResponse")
    public ArrayOfProducts getProducts(
        @WebParam(name = "uname", targetNamespace = "http://tempuri.org/")
        String uname,
        @WebParam(name = "upass", targetNamespace = "http://tempuri.org/")
        String upass);

}
